import './globals.css'
import type { Metadata } from 'next'
import { Exo } from 'next/font/google'

const exo = Exo({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Monster Land',
	description: 'Generated by create turbo',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}): JSX.Element {
	return (
		<html lang="en">
			<body className={exo.className}>{children}</body>
		</html>
	)
}
