import type { Metadata } from 'next'

import { exo } from './font'
import './globals.css'

export const metadata: Metadata = {
	description: 'Generated by create turbo',
	title: 'Monster Land',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}): JSX.Element {
	return (
		<html lang="en">
			<body className={`${exo.className} antialiased`}>{children}</body>
		</html>
	)
}
