import { customAlphabet } from "nanoid"
import { findMonsterInfoUID } from "./MonsterInfo.js"

const nanoid = customAlphabet("1234567890abcdef", 10)
const LEVEL_UP_DEFAULT_EXP = 1000

const Monster = [
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Bulbasaur"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Ivysaur"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Venusaur"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Charmander"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Charmeleon"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Charizard"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Squirtle"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Wartortle"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Blastoise"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Caterpie"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Metapod"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Butterfree"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Weedle"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Kakuna"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Beedrill"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Pidgey"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Pidgeotto"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Pidgeot"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Rattata"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Raticate"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Spearow"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Fearow"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Ekans"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Arbok"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Pikachu"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
		status: "owned",
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Raichu"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
	{
		uid: `M-${nanoid()}`,
		info_uid: findMonsterInfoUID("Pichu"),
		level_up_exp: LEVEL_UP_DEFAULT_EXP,
		attack: 50,
		defense: 50,
	},
]

export default Monster
